"""Guard against a name shipping as BOTH a command and a skill.

`jacked install` copies `jacked/data/commands/*.md` into `~/.claude/commands/`
and `jacked/data/skills/<name>/` into `~/.claude/skills/<name>/`. Claude Code
loads both trees, so a name present in both ships two full copies of the same
instruction document under one `/<name>`: whichever one wins is an accident of
resolution order, and the loser rots silently — edits land in a file nobody
reads. The 2026-09-01 migration moved ten names (dcr, qa, ux, whats-next,
docs-sync, lockdown, demo-video, qa-video, swarm-research, release) from
commands to skills; this test is what keeps a re-added command file from
quietly shadowing its skill.

Plain-pytest style matches the sibling shipped-content contract tests.
"""

from pathlib import Path

DATA = Path(__file__).resolve().parents[2] / "jacked" / "data"
COMMANDS = DATA / "commands"
SKILLS = DATA / "skills"


def test_no_name_ships_as_both_command_and_skill():
    command_names = {p.stem for p in COMMANDS.glob("*.md")}
    skill_names = {p.name for p in SKILLS.iterdir() if p.is_dir()}
    collisions = sorted(command_names & skill_names)
    assert not collisions, (
        "these names ship as BOTH jacked/data/commands/<name>.md and "
        f"jacked/data/skills/<name>/: {collisions}. Pick one home — a duplicate "
        "shadows the other at load time and the loser silently goes stale."
    )


def test_both_shipped_trees_are_non_empty():
    """The collision check above passes trivially if either tree is missing, so
    pin that both are actually populated."""
    assert {p.stem for p in COMMANDS.glob("*.md")}, "jacked/data/commands must ship command files"
    assert [p for p in SKILLS.iterdir() if p.is_dir()], "jacked/data/skills must ship skill dirs"


def test_repo_dogfood_tree_has_no_dual_names():
    """Same rule for this repo's own generated config: /jacked-setup writes ONE
    skill per target now, so a re-added .claude/commands/<name>.md would collide
    with .claude/skills/<name>/ exactly like the shipped tree. Scoped to skills
    that ARE /jacked-setup output (the 'Generated by' stamp) — a developer's own
    hand-authored command file at some other name is legitimate and none of our
    business (jacked-setup's HAND_AUTHORED rule)."""
    dot_claude = Path(__file__).resolve().parents[2] / ".claude"
    commands = dot_claude / "commands"
    command_names = {p.stem for p in commands.glob("*.md")} if commands.is_dir() else set()
    generated_skills = set()
    if (dot_claude / "skills").is_dir():
        for skill_md in (dot_claude / "skills").glob("*/SKILL.md"):
            if "Generated by /jacked-setup" in skill_md.read_text(encoding="utf-8"):
                generated_skills.add(skill_md.parent.name)
    assert generated_skills, (
        "no /jacked-setup-stamped skills found in .claude/skills — either the "
        "stamp text changed (update this test's grep) or the dogfood config is gone"
    )
    collisions = sorted(command_names & generated_skills)
    assert not collisions, (
        f".claude/ carries both a command and a generated skill for: {collisions}. "
        "The skill is the generated home now — delete the command file."
    )


def test_migrated_skills_have_preamble_then_single_engine_marker():
    """Producer-side shape contract, derived from the marker itself (no name
    list to drift): every shipped SKILL.md carrying `<!-- ENGINE -->` must have
    it exactly once, with the repo-dispatch preamble ABOVE it — the preamble is
    what routes /name into a /jacked-setup-generated repo skill, and below the
    marker it would leak into the Codex prompt instead."""
    marked = 0
    for skill_md in sorted(SKILLS.glob("*/SKILL.md")):
        text = skill_md.read_text(encoding="utf-8")
        lines = text.splitlines()
        idx = [i for i, line in enumerate(lines) if line.strip() == "<!-- ENGINE -->"]
        if not idx:
            continue
        marked += 1
        name = skill_md.parent.name
        assert len(idx) == 1, f"{name}: {len(idx)} engine markers, expected exactly 1"
        head = "\n".join(lines[: idx[0]])
        assert f".claude/skills/{name}/" in head, (
            f"{name}: repo-dispatch preamble missing or below the engine marker"
        )
    assert marked, "no marker-carrying skills found — the migrated set vanished"


def test_jacked_setup_gates_legacy_deletion_on_provenance():
    """The legacy-migration block must verify a .claude/commands/<target>.md is
    actually /jacked-setup output (the 'Generated by /jacked-setup' stamp)
    before instructing deletion — a filename collision alone must never drive
    a delete of a possibly hand-authored file."""
    text = (COMMANDS / "jacked-setup.md").read_text(encoding="utf-8")
    start = text.index("Legacy dual-format detection")
    end = text.index("DELETE the legacy", start)
    gate = text[start:end]
    assert "Generated by /jacked-setup" in gate and "HAND_AUTHORED" in gate, (
        "jacked-setup.md lost the provenance gate between legacy detection and "
        "the DELETE instruction"
    )
    assert "Never delete a `HAND_AUTHORED` file" in text
